### ISSUE TITLE
编译小程序，报错：internal/modules/cjs/loader.js:638     throw err;     ^  Error: Cannot find module 'caniuse-lite/dist/unpacker/agents'

### ISSUE THREAD

**Issue by MarsLeeJ** [js-newbee/taro-yanxuan#53]
� Taro v1.3.4

开始编译项目 taro-yanxuan
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'caniuse-lite/dist/unpacker/agents'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\taro-yanxuan\node_modules\_browserslist@3.2.8@browserslist\index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by wine1** [comment]
> � Taro v1.3.4
> 
> 开始编译项目 taro-yanxuan
> internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> Error: Cannot find module 'caniuse-lite/dist/unpacker/agents'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Module.require (internal/modules/cjs/loader.js:692:17)
> at require (internal/modules/cjs/helpers.js:25:18)
> at Object. (D:\taro-yanxuan\node_modules_browserslist@3.2.8@browserslist\index.js:4:14)
> at Module._compile (internal/modules/cjs/loader.js:778:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)

请问这个问题解决了吗 我也遇到了这个问题 一直找不到原因 求解答
